package IGU;

import AlgoBonito.*;

public class Ventana extends javax.swing.JFrame {
    CuentaNomina cNomina = new CuentaNomina(500);
    CuentaAhorro cAhorros = new CuentaAhorro(1000);
    CuentaInfantil cInfantil = new CuentaInfantil(50);

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbAhorros = new javax.swing.JRadioButton();
        rbNomina = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextArea();
        btnSaldo = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        rbNiños = new javax.swing.JRadioButton();
        btnRetiroDulces = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbAhorros);
        rbAhorros.setSelected(true);
        rbAhorros.setText("Cuenta de ahorros");
        rbAhorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAhorrosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbNomina);
        rbNomina.setText("Cuenta de Nomina");
        rbNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNominaActionPerformed(evt);
            }
        });

        txtMensajes.setBackground(new java.awt.Color(0, 0, 0));
        txtMensajes.setColumns(20);
        txtMensajes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensajes.setForeground(new java.awt.Color(255, 255, 255));
        txtMensajes.setRows(5);
        jScrollPane1.setViewportView(txtMensajes);

        btnSaldo.setText("Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        jLabel1.setText("Monto");

        txtMonto.setText("0.00");

        buttonGroup1.add(rbNiños);
        rbNiños.setText("Cuenta Kidz");
        rbNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNiñosActionPerformed(evt);
            }
        });

        btnRetiroDulces.setText("Retiro Dulces");
        btnRetiroDulces.setEnabled(false);
        btnRetiroDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroDulcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMonto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSaldo)
                                .addGap(18, 18, 18)
                                .addComponent(btnDepositar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetirar)
                                .addGap(18, 18, 18)
                                .addComponent(btnRetiroDulces))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbAhorros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNomina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNiños)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAhorros)
                    .addComponent(rbNomina)
                    .addComponent(rbNiños))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaldo)
                    .addComponent(btnDepositar)
                    .addComponent(btnRetirar)
                    .addComponent(btnRetiroDulces))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAhorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAhorrosActionPerformed
        // desactiva el boton de retirar dulces si no está seleccionado el radio button correcto
        btnRetiroDulces.setEnabled(false);
    }//GEN-LAST:event_rbAhorrosActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // Verifica de cual boton se va a consultar el saldo
        if (rbAhorros.isSelected()) {
            txtMensajes.setText(cAhorros.consultarSaldo());
        }else{
            if (rbNomina.isSelected()) {
                txtMensajes.setText(cNomina.consultarSaldo());
            }else{
                txtMensajes.setText(cInfantil.consultarSaldo());
            }
        }
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // Verifica de cual boton se va a realizar el metodo de deposito:
        if (rbAhorros.isSelected()) {
            txtMensajes.setText(cAhorros.deposito(Double.parseDouble(txtMonto.getText())));
        }else{
            if (rbNomina.isSelected()) {
                txtMensajes.setText(cNomina.deposito(Double.parseDouble(txtMonto.getText())));
            }else{
                txtMensajes.setText(cInfantil.deposito(Double.parseDouble(txtMonto.getText())));
            }        
        }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetiroDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroDulcesActionPerformed
        // Valida y realiza el retiro de dulces
        
            txtMensajes.setText(cInfantil.retiroDulces(Double.parseDouble(txtMonto.getText())));
    }//GEN-LAST:event_btnRetiroDulcesActionPerformed

    private void rbNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNiñosActionPerformed
        // activa el boton retiro dulces al seleccionar el radio button de cuenta kidz
        if (rbNiños.isSelected()) {
            btnRetiroDulces.setEnabled(true);
        }
    }//GEN-LAST:event_rbNiñosActionPerformed

    private void rbNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNominaActionPerformed
        // desactiva el boton de retirar dulces si no está seleccionado el radio button correcto
        btnRetiroDulces.setEnabled(false);
    }//GEN-LAST:event_rbNominaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // Verifica de cual boton se va a realizar el retiro
        if (rbAhorros.isSelected()) {
            txtMensajes.setText(cAhorros.retiro(Double.parseDouble(txtMonto.getText())));
        }else{
            if (rbNomina.isSelected()) {
                txtMensajes.setText(cNomina.retiro(Double.parseDouble(txtMonto.getText())));
            }else{
                txtMensajes.setText(cInfantil.retiro(Double.parseDouble(txtMonto.getText())));
            }        
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnRetiroDulces;
    private javax.swing.JButton btnSaldo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAhorros;
    private javax.swing.JRadioButton rbNiños;
    private javax.swing.JRadioButton rbNomina;
    private javax.swing.JTextArea txtMensajes;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
