package IGU;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import logica.CazadorImp;
import logica.GuerreroImp;
import logica.MagoImp;
import logica.Personaje;

public class VentanaRol extends javax.swing.JFrame {

    private static Personaje jugador1;
    private static Personaje jugador2;
    
    
    /**
     * Creates new form VentanaRol
     */
    public VentanaRol() {
        initComponents();
        lbJ1Foto.setIcon(new ImageIcon("src/main/java/libreri/mago/mago.jpg"));
        lbJ2Foto.setIcon(new ImageIcon("src/main/java/libreri/mago/mago.jpg"));
        
        btnJ1AtaqueUno.setIcon(new ImageIcon("src/main/java/libreri/mago/ataque1.png"));
        btnJ1AtaqueDos.setIcon(new ImageIcon("src/main/java/libreri/mago/ataque2.png"));
        
        btnJ2AtaqueUno.setIcon(new ImageIcon("src/main/java/libreri/mago/ataque1.png"));
        btnJ2AtaqueDos.setIcon(new ImageIcon("src/main/java/libreri/mago/ataque2.png"));
        
        lbJ1Raza.setIcon(new ImageIcon("src/main/java/libreri/raza/humano.png"));
        lbJ2Raza.setIcon(new ImageIcon("src/main/java/libreri/raza/humano.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbJ1Clase = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbJ1Raza = new javax.swing.JComboBox<>();
        lbJ1Foto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spJ1Vida = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spJ1Mana = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spJ1Nivel = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtJ1Nombre = new javax.swing.JTextField();
        lbJ1Raza = new javax.swing.JLabel();
        btnJ1AtaqueDos = new javax.swing.JButton();
        btnJ1AtaqueUno = new javax.swing.JButton();
        btnJ1CrearPersonaje = new javax.swing.JButton();
        lblJ1Vida = new javax.swing.JLabel();
        lblJ1mana = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbJ2Clase = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbJ2Raza = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        spJ2Vida = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        spJ2Mana = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        spJ2Nivel = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        txtJ2Nombre = new javax.swing.JTextField();
        lbJ2Foto = new javax.swing.JLabel();
        lbJ2Raza = new javax.swing.JLabel();
        btnJ2AtaqueUno = new javax.swing.JButton();
        btnJ2AtaqueDos = new javax.swing.JButton();
        btnJ2CrearPersonaje = new javax.swing.JButton();
        lblJ2Vida = new javax.swing.JLabel();
        lblJ2mana = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnReiniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego de Rol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Clase");

        cbJ1Clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago", "Guerrero", "Cazador" }));
        cbJ1Clase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJ1ClaseItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Raza ");

        cbJ1Raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Elfo", "Hada", "Duende", "Orco" }));
        cbJ1Raza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJ1RazaItemStateChanged(evt);
            }
        });

        lbJ1Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/mago.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Vida");

        spJ1Vida.setModel(new javax.swing.SpinnerNumberModel(100, 100, 1000, 5));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Maná");

        spJ1Mana.setModel(new javax.swing.SpinnerNumberModel(100, 100, 1000, 5));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Nivel");

        spJ1Nivel.setModel(new javax.swing.SpinnerNumberModel(1, 1, 25, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Nombre");

        lbJ1Raza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJ1Raza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/raza/humano.png"))); // NOI18N

        btnJ1AtaqueDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/ataque2.png"))); // NOI18N
        btnJ1AtaqueDos.setEnabled(false);
        btnJ1AtaqueDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ1AtaqueDosActionPerformed(evt);
            }
        });

        btnJ1AtaqueUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/ataque1.png"))); // NOI18N
        btnJ1AtaqueUno.setEnabled(false);
        btnJ1AtaqueUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ1AtaqueUnoActionPerformed(evt);
            }
        });

        btnJ1CrearPersonaje.setText("Crear Personaje");
        btnJ1CrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ1CrearPersonajeActionPerformed(evt);
            }
        });

        lblJ1Vida.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblJ1Vida.setText("Vida: ");

        lblJ1mana.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblJ1mana.setText("Maná:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbJ1Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJ1Raza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnJ1AtaqueUno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnJ1AtaqueDos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnJ1CrearPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblJ1Vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblJ1mana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spJ1Vida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spJ1Mana, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spJ1Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJ1Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJ1Raza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJ1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbJ1Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbJ1Raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spJ1Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(spJ1Mana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spJ1Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtJ1Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbJ1Raza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnJ1AtaqueUno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJ1AtaqueDos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJ1CrearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJ1Vida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJ1mana))
                    .addComponent(lbJ1Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(158, 59, 66));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Clase");

        cbJ2Clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mago", "Guerrero", "Cazador" }));
        cbJ2Clase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJ2ClaseItemStateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Raza ");

        cbJ2Raza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Humano", "Elfo", "Hada", "Duende", "Orco" }));
        cbJ2Raza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJ2RazaItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("Vida");

        spJ2Vida.setModel(new javax.swing.SpinnerNumberModel(100, 100, 1000, 5));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("Maná");

        spJ2Mana.setModel(new javax.swing.SpinnerNumberModel(100, 100, 1000, 5));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setText("Nivel");

        spJ2Nivel.setModel(new javax.swing.SpinnerNumberModel(1, 1, 25, 1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel16.setText("Nombre");

        lbJ2Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/mago.jpg"))); // NOI18N

        lbJ2Raza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJ2Raza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/raza/humano.png"))); // NOI18N

        btnJ2AtaqueUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/ataque1.png"))); // NOI18N
        btnJ2AtaqueUno.setEnabled(false);
        btnJ2AtaqueUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ2AtaqueUnoActionPerformed(evt);
            }
        });

        btnJ2AtaqueDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libreri/mago/ataque2.png"))); // NOI18N
        btnJ2AtaqueDos.setEnabled(false);
        btnJ2AtaqueDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ2AtaqueDosActionPerformed(evt);
            }
        });

        btnJ2CrearPersonaje.setText("Crear Personaje");
        btnJ2CrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJ2CrearPersonajeActionPerformed(evt);
            }
        });

        lblJ2Vida.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblJ2Vida.setText("Vida: ");

        lblJ2mana.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblJ2mana.setText("Maná:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbJ2Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJ2CrearPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnJ2AtaqueUno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnJ2AtaqueDos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbJ2Raza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJ2Vida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJ2mana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJ2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJ2Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbJ2Raza, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spJ2Vida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spJ2Mana, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spJ2Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbJ2Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbJ2Raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spJ2Vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(spJ2Mana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(spJ2Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtJ2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbJ2Raza, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnJ2AtaqueUno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJ2AtaqueDos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJ2CrearPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJ2Vida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJ2mana))
                    .addComponent(lbJ2Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        jScrollPane1.setViewportView(jTextPane1);

        btnReiniciarJuego.setText("reiniciar"); // NOI18N
        btnReiniciarJuego.setEnabled(false);
        btnReiniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnReiniciarJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJ1ClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJ1ClaseItemStateChanged
        String clase = cbJ1Clase.getSelectedItem().toString().toLowerCase();
        lbJ1Foto.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/"+clase+".jpg"));
        btnJ1AtaqueUno.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/ataque1.png"));
        btnJ1AtaqueDos.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/ataque2.png"));
    }//GEN-LAST:event_cbJ1ClaseItemStateChanged

    private void cbJ2ClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJ2ClaseItemStateChanged
        String clase = cbJ2Clase.getSelectedItem().toString().toLowerCase();
        lbJ2Foto.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/"+clase+".jpg"));
        btnJ2AtaqueUno.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/ataque1.png"));
        btnJ2AtaqueDos.setIcon(new ImageIcon("src/main/java/libreri/"+clase+"/ataque2.png"));
    }//GEN-LAST:event_cbJ2ClaseItemStateChanged

    private void cbJ1RazaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJ1RazaItemStateChanged
        String raza = cbJ1Raza.getSelectedItem().toString().toLowerCase();
        lbJ1Raza.setIcon(new ImageIcon("src/main/java/libreri/raza/"+raza+".png"));
    }//GEN-LAST:event_cbJ1RazaItemStateChanged

    private void cbJ2RazaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJ2RazaItemStateChanged
        String raza = cbJ2Raza.getSelectedItem().toString().toLowerCase();
        lbJ2Raza.setIcon(new ImageIcon("src/main/java/libreri/raza/"+raza+".png"));
    }//GEN-LAST:event_cbJ2RazaItemStateChanged

    private void btnJ1CrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ1CrearPersonajeActionPerformed
        lblJ1Vida.setText("vida: "+ spJ1Vida.getValue().toString());
        lblJ1mana.setText("Maná: "+ spJ1Mana.getValue().toString());
        
        switch ((String)cbJ1Clase.getSelectedItem()){
            case "Mago" ->{
                jugador1 = new MagoImp(txtJ1Nombre.getText(),(int) spJ1Vida.getValue(), (int) spJ1Mana.getValue(), (int) spJ1Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador1.mostrarInformacion(), Color.DARK_GRAY);
            }
            case "Guerrero" ->{
                jugador1 = new GuerreroImp(txtJ1Nombre.getText(),(int) spJ1Vida.getValue(), (int) spJ1Mana.getValue(), (int) spJ1Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador1.mostrarInformacion(), Color.DARK_GRAY);
            }
            case "Cazador" ->{
                jugador1 = new CazadorImp(txtJ1Nombre.getText(),(int) spJ1Vida.getValue(), (int) spJ1Mana.getValue(), (int) spJ1Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador1.mostrarInformacion(), Color.DARK_GRAY);
            }
            default -> throw new AssertionError();
        }
        
        cbJ1Clase.setEnabled(false);
        cbJ1Raza.setEnabled(false);
        spJ1Vida.setEnabled(false);
        spJ1Mana.setEnabled(false);
        spJ1Nivel.setEnabled(false);
        txtJ1Nombre.setEnabled(false);
        btnJ1AtaqueUno.setEnabled(true);
        btnJ1AtaqueDos.setEnabled(true);
        btnJ1CrearPersonaje.setEnabled(false);
    }//GEN-LAST:event_btnJ1CrearPersonajeActionPerformed

    private void btnJ2CrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ2CrearPersonajeActionPerformed
        lblJ2Vida.setText("vida: "+ spJ2Vida.getValue().toString());
        lblJ2mana.setText("Maná: "+ spJ2Mana.getValue().toString());
        
        switch ((String)cbJ2Clase.getSelectedItem()){
            case "Mago" ->{
                jugador2 = new MagoImp(txtJ2Nombre.getText(),(int) spJ2Vida.getValue(), (int) spJ2Mana.getValue(), (int) spJ2Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador2.mostrarInformacion(), Color.DARK_GRAY);
            }
            case "Guerrero" ->{
                jugador2 = new GuerreroImp(txtJ2Nombre.getText(),(int) spJ2Vida.getValue(), (int) spJ2Mana.getValue(), (int) spJ2Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador2.mostrarInformacion(), Color.DARK_GRAY);
            }
            case "Cazador" ->{
                jugador2 = new CazadorImp(txtJ2Nombre.getText(),(int) spJ2Vida.getValue(), (int) spJ2Mana.getValue(), (int) spJ2Nivel.getValue());
                agregarLineaColor(jTextPane1, jugador2.mostrarInformacion(), Color.DARK_GRAY);
            }
            default -> throw new AssertionError();
        }
        
        cbJ2Clase.setEnabled(false);
        cbJ2Raza.setEnabled(false);
        spJ2Vida.setEnabled(false);
        spJ2Mana.setEnabled(false);
        spJ2Nivel.setEnabled(false);
        txtJ2Nombre.setEnabled(false);
        btnJ2AtaqueUno.setEnabled(true);
        btnJ2AtaqueDos.setEnabled(true);
        btnJ2CrearPersonaje.setEnabled(false);
    }//GEN-LAST:event_btnJ2CrearPersonajeActionPerformed

    private void btnJ1AtaqueUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ1AtaqueUnoActionPerformed
        agregarLineaColor(jTextPane1, jugador1.atacar1(jugador2), Color.BLACK);
        lblJ1mana.setText("Maná: "+ jugador1.getMana());
        lblJ2Vida.setText("vida: "+ jugador2.getVida());
        btnJ1AtaqueUno.setEnabled(false);
        btnJ1AtaqueDos.setEnabled(false);
        if (jugador2.getVida()>=1) {
            btnJ2AtaqueUno.setEnabled(true);
            btnJ2AtaqueDos.setEnabled(true);
        }else{
            btnJ2AtaqueUno.setEnabled(false);
            btnJ2AtaqueDos.setEnabled(false);
            lblJ2Vida.setText("Vida: 0");
            btnReiniciarJuego.setEnabled(true);
        }
    }//GEN-LAST:event_btnJ1AtaqueUnoActionPerformed

    private void btnJ1AtaqueDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ1AtaqueDosActionPerformed
        agregarLineaColor(jTextPane1, jugador1.atacar2(jugador2), Color.BLACK);
        lblJ1mana.setText("Maná: "+ jugador1.getMana());
        lblJ2Vida.setText("vida: "+ jugador2.getVida());
        btnJ1AtaqueUno.setEnabled(false);
        btnJ1AtaqueDos.setEnabled(false);
        lblJ1Vida.setText("vida: "+ spJ1Vida.getValue().toString());
        lblJ1mana.setText("Maná: "+ spJ1Mana.getValue().toString());
        if (jugador2.getVida()>=1) {
            btnJ2AtaqueUno.setEnabled(true);
            btnJ2AtaqueDos.setEnabled(true);
        }else{
            btnJ2AtaqueUno.setEnabled(false);
            btnJ2AtaqueDos.setEnabled(false);
            lblJ2Vida.setText("Vida: 0");
            btnReiniciarJuego.setEnabled(true);
        }
    }//GEN-LAST:event_btnJ1AtaqueDosActionPerformed

    private void btnJ2AtaqueUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ2AtaqueUnoActionPerformed
        agregarLineaColor(jTextPane1, jugador2.atacar1(jugador1), Color.BLACK);
        lblJ2mana.setText("Maná: "+ jugador2.getMana());
        lblJ1Vida.setText("vida: "+ jugador1.getVida());
        btnJ2AtaqueUno.setEnabled(false);
        btnJ2AtaqueDos.setEnabled(false);
        if (jugador1.getVida()>=1) {
            btnJ1AtaqueUno.setEnabled(true);
            btnJ1AtaqueDos.setEnabled(true);
        }else{
            btnJ1AtaqueUno.setEnabled(false);
            btnJ1AtaqueDos.setEnabled(false);
            lblJ1Vida.setText("Vida: 0");
            btnReiniciarJuego.setEnabled(true);
        }
    }//GEN-LAST:event_btnJ2AtaqueUnoActionPerformed

    private void btnJ2AtaqueDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJ2AtaqueDosActionPerformed
        agregarLineaColor(jTextPane1, jugador2.atacar1(jugador1), Color.BLACK);
        lblJ2mana.setText("Maná: "+ jugador2.getMana());
        lblJ1Vida.setText("vida: "+ jugador1.getVida());
        btnJ2AtaqueUno.setEnabled(false);
        btnJ2AtaqueDos.setEnabled(false);
        if (jugador1.getVida()>=1) {
            btnJ1AtaqueUno.setEnabled(true);
            btnJ1AtaqueDos.setEnabled(true);
        }else{
            btnJ1AtaqueUno.setEnabled(false);
            btnJ1AtaqueDos.setEnabled(false);
            lblJ1Vida.setText("Vida: 0");
            btnReiniciarJuego.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnJ2AtaqueDosActionPerformed

    private void btnReiniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarJuegoActionPerformed
        cbJ1Clase.setEnabled(true);
        cbJ1Raza.setEnabled(true);
        spJ1Vida.setEnabled(true);
        spJ1Mana.setEnabled(true);
        spJ1Nivel.setEnabled(true);
        txtJ1Nombre.setEnabled(true);
        btnJ1CrearPersonaje.setEnabled(true);
        lblJ1Vida.setText("Vida: ");
        lblJ1mana.setText("Maná: ");
        
        cbJ2Clase.setEnabled(true);
        cbJ2Raza.setEnabled(true);
        spJ2Vida.setEnabled(true);
        spJ2Mana.setEnabled(true);
        spJ2Nivel.setEnabled(true);
        txtJ2Nombre.setEnabled(true);
        btnJ2CrearPersonaje.setEnabled(true);
        lblJ2Vida.setText("Vida: ");
        lblJ2mana.setText("Maná: ");
    }//GEN-LAST:event_btnReiniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaRol().setVisible(true);
        });
    }
    
    public void agregarLineaColor(JTextPane textPane, String texto, Color color) {
        // Crear un estilo con el color especificado
        SimpleAttributeSet estilo = new SimpleAttributeSet();
        StyleConstants.setForeground(estilo, color);

        // Insertar el texto con el estilo
        try {
            textPane.getDocument().insertString(textPane.getDocument().getLength(), texto + "\n", estilo);
        } catch (BadLocationException e) {
            System.out.println("no furula");
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJ1AtaqueDos;
    private javax.swing.JButton btnJ1AtaqueUno;
    private javax.swing.JButton btnJ1CrearPersonaje;
    private javax.swing.JButton btnJ2AtaqueDos;
    private javax.swing.JButton btnJ2AtaqueUno;
    private javax.swing.JButton btnJ2CrearPersonaje;
    private javax.swing.JButton btnReiniciarJuego;
    private javax.swing.JComboBox<String> cbJ1Clase;
    private javax.swing.JComboBox<String> cbJ1Raza;
    private javax.swing.JComboBox<String> cbJ2Clase;
    private javax.swing.JComboBox<String> cbJ2Raza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lbJ1Foto;
    private javax.swing.JLabel lbJ1Raza;
    private javax.swing.JLabel lbJ2Foto;
    private javax.swing.JLabel lbJ2Raza;
    private javax.swing.JLabel lblJ1Vida;
    private javax.swing.JLabel lblJ1mana;
    private javax.swing.JLabel lblJ2Vida;
    private javax.swing.JLabel lblJ2mana;
    private javax.swing.JSpinner spJ1Mana;
    private javax.swing.JSpinner spJ1Nivel;
    private javax.swing.JSpinner spJ1Vida;
    private javax.swing.JSpinner spJ2Mana;
    private javax.swing.JSpinner spJ2Nivel;
    private javax.swing.JSpinner spJ2Vida;
    private javax.swing.JTextField txtJ1Nombre;
    private javax.swing.JTextField txtJ2Nombre;
    // End of variables declaration//GEN-END:variables
}
